on:
  push:
    branches:
      - main

name: build
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Build wasm
        run: GOOS=js GOARCH=wasm go build -o game1.wasm ./cmd/game1
        working-directory: src

